CREATE TABLE sessions (
  id INT NOT NULL AUTO_INCREMENT,
  sessionkey VARCHAR(8) NOT NULL,
  user_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  short_title VARCHAR(255) NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT session_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;