CREATE TABLE features (
  id INT NOT NULL AUTO_INCREMENT,
  session_id INT NOT NULL,
  slides TINYINT(1) NOT NULL DEFAULT 0,
  flaschards TINYINT(1) NOT NULL DEFAULT 0,
  peerGrading TINYINT(1) NOT NULL DEFAULT 0,
  peerInstruction TINYINT(1) NOT NULL DEFAULT 0,
  comments TINYINT(1) NOT NULL DEFAULT 0,
  tileView TINYINT(1) NOT NULL DEFAULT 0,
  jitt TINYINT(1) NOT NULL DEFAULT 0,
  learningProgress TINYINT(1) NOT NULL DEFAULT 0,
  feedback TINYINT(1) NOT NULL DEFAULT 0,
  liveQuestions TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY(id),
  CONSTRAINT features_session_fk FOREIGN KEY (session_id) REFERENCES sessions(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;
