CREATE TABLE features (
  id INT NOT NULL AUTO_INCREMENT,
  session_id INT NOT NULL,
  slides TINYINT(1) NOT NULL DEFAULT 0,
  flashcards TINYINT(1) NOT NULL DEFAULT 0,
  peer_grading TINYINT(1) NOT NULL DEFAULT 0,
  peer_instruction TINYINT(1) NOT NULL DEFAULT 0,
  comments TINYINT(1) NOT NULL DEFAULT 0,
  tile_view TINYINT(1) NOT NULL DEFAULT 0,
  jitt TINYINT(1) NOT NULL DEFAULT 0,
  learning_progress TINYINT(1) NOT NULL DEFAULT 0,
  feedback TINYINT(1) NOT NULL DEFAULT 0,
  live_questions TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY(id),
  CONSTRAINT features_session_fk FOREIGN KEY (session_id) REFERENCES sessions(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;
